name: Lint and Test

on: pull_request

env:
  SPRING_PROFILES_ACTIVE: test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build && ./gradlew spotlessCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test
